// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/requests/request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ChatServer.Transmissions {

  /// <summary>Holder for reflection information generated from proto/requests/request.proto</summary>
  public static partial class RequestReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/requests/request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxwcm90by9yZXF1ZXN0cy9yZXF1ZXN0LnByb3RvEhhDaGF0U2VydmVyLlRy",
            "YW5zbWlzc2lvbnMaJnByb3RvL3JlcXVlc3RzL3NlcnZlckpvaW5SZXF1ZXN0",
            "LnByb3RvGiRwcm90by9yZXF1ZXN0cy9jaGF0Sm9pblJlcXVlc3QucHJvdG8a",
            "JXByb3RvL3JlcXVlc3RzL2NoYXRMZWF2ZVJlcXVlc3QucHJvdG8aJnByb3Rv",
            "L3JlcXVlc3RzL25hbWVDaGFuZ2VSZXF1ZXN0LnByb3RvIrYCCgdSZXF1ZXN0",
            "EkgKEXNlcnZlckpvaW5SZXF1ZXN0GAEgASgLMisuQ2hhdFNlcnZlci5UcmFu",
            "c21pc3Npb25zLlNlcnZlckpvaW5SZXF1ZXN0SAASRAoPQ2hhdEpvaW5SZXF1",
            "ZXN0GAIgASgLMikuQ2hhdFNlcnZlci5UcmFuc21pc3Npb25zLkNoYXRKb2lu",
            "UmVxdWVzdEgAEkYKEGNoYXRMZWF2ZVJlcXVlc3QYAyABKAsyKi5DaGF0U2Vy",
            "dmVyLlRyYW5zbWlzc2lvbnMuQ2hhdExlYXZlUmVxdWVzdEgAEkgKEW5hbWVD",
            "aGFuZ2VSZXF1ZXN0GAQgASgLMisuQ2hhdFNlcnZlci5UcmFuc21pc3Npb25z",
            "Lk5hbWVDaGFuZ2VSZXF1ZXN0SABCCQoHcmVxdWVzdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ChatServer.Transmissions.ServerJoinRequestReflection.Descriptor, global::ChatServer.Transmissions.ChatJoinRequestReflection.Descriptor, global::ChatServer.Transmissions.ChatLeaveRequestReflection.Descriptor, global::ChatServer.Transmissions.NameChangeRequestReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Transmissions.Request), global::ChatServer.Transmissions.Request.Parser, new[]{ "ServerJoinRequest", "ChatJoinRequest", "ChatLeaveRequest", "NameChangeRequest" }, new[]{ "Request" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Transmissions.RequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      switch (other.RequestCase) {
        case RequestOneofCase.ServerJoinRequest:
          ServerJoinRequest = other.ServerJoinRequest.Clone();
          break;
        case RequestOneofCase.ChatJoinRequest:
          ChatJoinRequest = other.ChatJoinRequest.Clone();
          break;
        case RequestOneofCase.ChatLeaveRequest:
          ChatLeaveRequest = other.ChatLeaveRequest.Clone();
          break;
        case RequestOneofCase.NameChangeRequest:
          NameChangeRequest = other.NameChangeRequest.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "serverJoinRequest" field.</summary>
    public const int ServerJoinRequestFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Transmissions.ServerJoinRequest ServerJoinRequest {
      get { return requestCase_ == RequestOneofCase.ServerJoinRequest ? (global::ChatServer.Transmissions.ServerJoinRequest) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.ServerJoinRequest;
      }
    }

    /// <summary>Field number for the "ChatJoinRequest" field.</summary>
    public const int ChatJoinRequestFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Transmissions.ChatJoinRequest ChatJoinRequest {
      get { return requestCase_ == RequestOneofCase.ChatJoinRequest ? (global::ChatServer.Transmissions.ChatJoinRequest) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.ChatJoinRequest;
      }
    }

    /// <summary>Field number for the "chatLeaveRequest" field.</summary>
    public const int ChatLeaveRequestFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Transmissions.ChatLeaveRequest ChatLeaveRequest {
      get { return requestCase_ == RequestOneofCase.ChatLeaveRequest ? (global::ChatServer.Transmissions.ChatLeaveRequest) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.ChatLeaveRequest;
      }
    }

    /// <summary>Field number for the "nameChangeRequest" field.</summary>
    public const int NameChangeRequestFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Transmissions.NameChangeRequest NameChangeRequest {
      get { return requestCase_ == RequestOneofCase.NameChangeRequest ? (global::ChatServer.Transmissions.NameChangeRequest) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.NameChangeRequest;
      }
    }

    private object request_;
    /// <summary>Enum of possible cases for the "request" oneof.</summary>
    public enum RequestOneofCase {
      None = 0,
      ServerJoinRequest = 1,
      ChatJoinRequest = 2,
      ChatLeaveRequest = 3,
      NameChangeRequest = 4,
    }
    private RequestOneofCase requestCase_ = RequestOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestOneofCase RequestCase {
      get { return requestCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRequest() {
      requestCase_ = RequestOneofCase.None;
      request_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ServerJoinRequest, other.ServerJoinRequest)) return false;
      if (!object.Equals(ChatJoinRequest, other.ChatJoinRequest)) return false;
      if (!object.Equals(ChatLeaveRequest, other.ChatLeaveRequest)) return false;
      if (!object.Equals(NameChangeRequest, other.NameChangeRequest)) return false;
      if (RequestCase != other.RequestCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (requestCase_ == RequestOneofCase.ServerJoinRequest) hash ^= ServerJoinRequest.GetHashCode();
      if (requestCase_ == RequestOneofCase.ChatJoinRequest) hash ^= ChatJoinRequest.GetHashCode();
      if (requestCase_ == RequestOneofCase.ChatLeaveRequest) hash ^= ChatLeaveRequest.GetHashCode();
      if (requestCase_ == RequestOneofCase.NameChangeRequest) hash ^= NameChangeRequest.GetHashCode();
      hash ^= (int) requestCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (requestCase_ == RequestOneofCase.ServerJoinRequest) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerJoinRequest);
      }
      if (requestCase_ == RequestOneofCase.ChatJoinRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatJoinRequest);
      }
      if (requestCase_ == RequestOneofCase.ChatLeaveRequest) {
        output.WriteRawTag(26);
        output.WriteMessage(ChatLeaveRequest);
      }
      if (requestCase_ == RequestOneofCase.NameChangeRequest) {
        output.WriteRawTag(34);
        output.WriteMessage(NameChangeRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (requestCase_ == RequestOneofCase.ServerJoinRequest) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerJoinRequest);
      }
      if (requestCase_ == RequestOneofCase.ChatJoinRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatJoinRequest);
      }
      if (requestCase_ == RequestOneofCase.ChatLeaveRequest) {
        output.WriteRawTag(26);
        output.WriteMessage(ChatLeaveRequest);
      }
      if (requestCase_ == RequestOneofCase.NameChangeRequest) {
        output.WriteRawTag(34);
        output.WriteMessage(NameChangeRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (requestCase_ == RequestOneofCase.ServerJoinRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerJoinRequest);
      }
      if (requestCase_ == RequestOneofCase.ChatJoinRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatJoinRequest);
      }
      if (requestCase_ == RequestOneofCase.ChatLeaveRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatLeaveRequest);
      }
      if (requestCase_ == RequestOneofCase.NameChangeRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NameChangeRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      switch (other.RequestCase) {
        case RequestOneofCase.ServerJoinRequest:
          if (ServerJoinRequest == null) {
            ServerJoinRequest = new global::ChatServer.Transmissions.ServerJoinRequest();
          }
          ServerJoinRequest.MergeFrom(other.ServerJoinRequest);
          break;
        case RequestOneofCase.ChatJoinRequest:
          if (ChatJoinRequest == null) {
            ChatJoinRequest = new global::ChatServer.Transmissions.ChatJoinRequest();
          }
          ChatJoinRequest.MergeFrom(other.ChatJoinRequest);
          break;
        case RequestOneofCase.ChatLeaveRequest:
          if (ChatLeaveRequest == null) {
            ChatLeaveRequest = new global::ChatServer.Transmissions.ChatLeaveRequest();
          }
          ChatLeaveRequest.MergeFrom(other.ChatLeaveRequest);
          break;
        case RequestOneofCase.NameChangeRequest:
          if (NameChangeRequest == null) {
            NameChangeRequest = new global::ChatServer.Transmissions.NameChangeRequest();
          }
          NameChangeRequest.MergeFrom(other.NameChangeRequest);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::ChatServer.Transmissions.ServerJoinRequest subBuilder = new global::ChatServer.Transmissions.ServerJoinRequest();
            if (requestCase_ == RequestOneofCase.ServerJoinRequest) {
              subBuilder.MergeFrom(ServerJoinRequest);
            }
            input.ReadMessage(subBuilder);
            ServerJoinRequest = subBuilder;
            break;
          }
          case 18: {
            global::ChatServer.Transmissions.ChatJoinRequest subBuilder = new global::ChatServer.Transmissions.ChatJoinRequest();
            if (requestCase_ == RequestOneofCase.ChatJoinRequest) {
              subBuilder.MergeFrom(ChatJoinRequest);
            }
            input.ReadMessage(subBuilder);
            ChatJoinRequest = subBuilder;
            break;
          }
          case 26: {
            global::ChatServer.Transmissions.ChatLeaveRequest subBuilder = new global::ChatServer.Transmissions.ChatLeaveRequest();
            if (requestCase_ == RequestOneofCase.ChatLeaveRequest) {
              subBuilder.MergeFrom(ChatLeaveRequest);
            }
            input.ReadMessage(subBuilder);
            ChatLeaveRequest = subBuilder;
            break;
          }
          case 34: {
            global::ChatServer.Transmissions.NameChangeRequest subBuilder = new global::ChatServer.Transmissions.NameChangeRequest();
            if (requestCase_ == RequestOneofCase.NameChangeRequest) {
              subBuilder.MergeFrom(NameChangeRequest);
            }
            input.ReadMessage(subBuilder);
            NameChangeRequest = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::ChatServer.Transmissions.ServerJoinRequest subBuilder = new global::ChatServer.Transmissions.ServerJoinRequest();
            if (requestCase_ == RequestOneofCase.ServerJoinRequest) {
              subBuilder.MergeFrom(ServerJoinRequest);
            }
            input.ReadMessage(subBuilder);
            ServerJoinRequest = subBuilder;
            break;
          }
          case 18: {
            global::ChatServer.Transmissions.ChatJoinRequest subBuilder = new global::ChatServer.Transmissions.ChatJoinRequest();
            if (requestCase_ == RequestOneofCase.ChatJoinRequest) {
              subBuilder.MergeFrom(ChatJoinRequest);
            }
            input.ReadMessage(subBuilder);
            ChatJoinRequest = subBuilder;
            break;
          }
          case 26: {
            global::ChatServer.Transmissions.ChatLeaveRequest subBuilder = new global::ChatServer.Transmissions.ChatLeaveRequest();
            if (requestCase_ == RequestOneofCase.ChatLeaveRequest) {
              subBuilder.MergeFrom(ChatLeaveRequest);
            }
            input.ReadMessage(subBuilder);
            ChatLeaveRequest = subBuilder;
            break;
          }
          case 34: {
            global::ChatServer.Transmissions.NameChangeRequest subBuilder = new global::ChatServer.Transmissions.NameChangeRequest();
            if (requestCase_ == RequestOneofCase.NameChangeRequest) {
              subBuilder.MergeFrom(NameChangeRequest);
            }
            input.ReadMessage(subBuilder);
            NameChangeRequest = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
