// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/transmission.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ChatServer.Transmissions {

  /// <summary>Holder for reflection information generated from proto/transmission.proto</summary>
  public static partial class TransmissionReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/transmission.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransmissionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90by90cmFuc21pc3Npb24ucHJvdG8SGENoYXRTZXJ2ZXIuVHJhbnNt",
            "aXNzaW9ucxoccHJvdG8vbWVzc2FnZXMvbWVzc2FnZS5wcm90bxoccHJvdG8v",
            "cmVxdWVzdHMvcmVxdWVzdC5wcm90bxoecHJvdG8vcmVzcG9uc2VzL3Jlc3Bv",
            "bnNlLnByb3RvIuIBCgxUcmFuc21pc3Npb24SEQoJc2lnbmF0dXJlGAEgASgM",
            "EhAKCHNlbmRlcklEGAIgASgMEjQKB21lc3NhZ2UYAyABKAsyIS5DaGF0U2Vy",
            "dmVyLlRyYW5zbWlzc2lvbnMuTWVzc2FnZUgAEjQKB3JlcXVlc3QYBCABKAsy",
            "IS5DaGF0U2VydmVyLlRyYW5zbWlzc2lvbnMuUmVxdWVzdEgAEjYKCHJlc3Bv",
            "bnNlGAUgASgLMiIuQ2hhdFNlcnZlci5UcmFuc21pc3Npb25zLlJlc3BvbnNl",
            "SABCCQoHY29udGVudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ChatServer.Transmissions.MessageReflection.Descriptor, global::ChatServer.Transmissions.RequestReflection.Descriptor, global::ChatServer.Transmissions.ResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ChatServer.Transmissions.Transmission), global::ChatServer.Transmissions.Transmission.Parser, new[]{ "Signature", "SenderID", "Message", "Request", "Response" }, new[]{ "Content" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Transmission : pb::IMessage<Transmission>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Transmission> _parser = new pb::MessageParser<Transmission>(() => new Transmission());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Transmission> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChatServer.Transmissions.TransmissionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transmission() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transmission(Transmission other) : this() {
      signature_ = other.signature_;
      senderID_ = other.senderID_;
      switch (other.ContentCase) {
        case ContentOneofCase.Message:
          Message = other.Message.Clone();
          break;
        case ContentOneofCase.Request:
          Request = other.Request.Clone();
          break;
        case ContentOneofCase.Response:
          Response = other.Response.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Transmission Clone() {
      return new Transmission(this);
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 1;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "senderID" field.</summary>
    public const int SenderIDFieldNumber = 2;
    private pb::ByteString senderID_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SenderID {
      get { return senderID_; }
      set {
        senderID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Transmissions.Message Message {
      get { return contentCase_ == ContentOneofCase.Message ? (global::ChatServer.Transmissions.Message) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.Message;
      }
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Transmissions.Request Request {
      get { return contentCase_ == ContentOneofCase.Request ? (global::ChatServer.Transmissions.Request) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.Request;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ChatServer.Transmissions.Response Response {
      get { return contentCase_ == ContentOneofCase.Response ? (global::ChatServer.Transmissions.Response) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.Response;
      }
    }

    private object content_;
    /// <summary>Enum of possible cases for the "content" oneof.</summary>
    public enum ContentOneofCase {
      None = 0,
      Message = 3,
      Request = 4,
      Response = 5,
    }
    private ContentOneofCase contentCase_ = ContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentOneofCase ContentCase {
      get { return contentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearContent() {
      contentCase_ = ContentOneofCase.None;
      content_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Transmission);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Transmission other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Signature != other.Signature) return false;
      if (SenderID != other.SenderID) return false;
      if (!object.Equals(Message, other.Message)) return false;
      if (!object.Equals(Request, other.Request)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      if (ContentCase != other.ContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (SenderID.Length != 0) hash ^= SenderID.GetHashCode();
      if (contentCase_ == ContentOneofCase.Message) hash ^= Message.GetHashCode();
      if (contentCase_ == ContentOneofCase.Request) hash ^= Request.GetHashCode();
      if (contentCase_ == ContentOneofCase.Response) hash ^= Response.GetHashCode();
      hash ^= (int) contentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Signature.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Signature);
      }
      if (SenderID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(SenderID);
      }
      if (contentCase_ == ContentOneofCase.Message) {
        output.WriteRawTag(26);
        output.WriteMessage(Message);
      }
      if (contentCase_ == ContentOneofCase.Request) {
        output.WriteRawTag(34);
        output.WriteMessage(Request);
      }
      if (contentCase_ == ContentOneofCase.Response) {
        output.WriteRawTag(42);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Signature.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Signature);
      }
      if (SenderID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(SenderID);
      }
      if (contentCase_ == ContentOneofCase.Message) {
        output.WriteRawTag(26);
        output.WriteMessage(Message);
      }
      if (contentCase_ == ContentOneofCase.Request) {
        output.WriteRawTag(34);
        output.WriteMessage(Request);
      }
      if (contentCase_ == ContentOneofCase.Response) {
        output.WriteRawTag(42);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (SenderID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SenderID);
      }
      if (contentCase_ == ContentOneofCase.Message) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (contentCase_ == ContentOneofCase.Request) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (contentCase_ == ContentOneofCase.Response) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Transmission other) {
      if (other == null) {
        return;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      if (other.SenderID.Length != 0) {
        SenderID = other.SenderID;
      }
      switch (other.ContentCase) {
        case ContentOneofCase.Message:
          if (Message == null) {
            Message = new global::ChatServer.Transmissions.Message();
          }
          Message.MergeFrom(other.Message);
          break;
        case ContentOneofCase.Request:
          if (Request == null) {
            Request = new global::ChatServer.Transmissions.Request();
          }
          Request.MergeFrom(other.Request);
          break;
        case ContentOneofCase.Response:
          if (Response == null) {
            Response = new global::ChatServer.Transmissions.Response();
          }
          Response.MergeFrom(other.Response);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Signature = input.ReadBytes();
            break;
          }
          case 18: {
            SenderID = input.ReadBytes();
            break;
          }
          case 26: {
            global::ChatServer.Transmissions.Message subBuilder = new global::ChatServer.Transmissions.Message();
            if (contentCase_ == ContentOneofCase.Message) {
              subBuilder.MergeFrom(Message);
            }
            input.ReadMessage(subBuilder);
            Message = subBuilder;
            break;
          }
          case 34: {
            global::ChatServer.Transmissions.Request subBuilder = new global::ChatServer.Transmissions.Request();
            if (contentCase_ == ContentOneofCase.Request) {
              subBuilder.MergeFrom(Request);
            }
            input.ReadMessage(subBuilder);
            Request = subBuilder;
            break;
          }
          case 42: {
            global::ChatServer.Transmissions.Response subBuilder = new global::ChatServer.Transmissions.Response();
            if (contentCase_ == ContentOneofCase.Response) {
              subBuilder.MergeFrom(Response);
            }
            input.ReadMessage(subBuilder);
            Response = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Signature = input.ReadBytes();
            break;
          }
          case 18: {
            SenderID = input.ReadBytes();
            break;
          }
          case 26: {
            global::ChatServer.Transmissions.Message subBuilder = new global::ChatServer.Transmissions.Message();
            if (contentCase_ == ContentOneofCase.Message) {
              subBuilder.MergeFrom(Message);
            }
            input.ReadMessage(subBuilder);
            Message = subBuilder;
            break;
          }
          case 34: {
            global::ChatServer.Transmissions.Request subBuilder = new global::ChatServer.Transmissions.Request();
            if (contentCase_ == ContentOneofCase.Request) {
              subBuilder.MergeFrom(Request);
            }
            input.ReadMessage(subBuilder);
            Request = subBuilder;
            break;
          }
          case 42: {
            global::ChatServer.Transmissions.Response subBuilder = new global::ChatServer.Transmissions.Response();
            if (contentCase_ == ContentOneofCase.Response) {
              subBuilder.MergeFrom(Response);
            }
            input.ReadMessage(subBuilder);
            Response = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
