using System.Security.Cryptography;

namespace ChatServer
{
    public class User
    {
        public string Name;
        public byte[] ID;


        //Temp constructer with autogenerated ID
        public User(string name) : this((new RSACryptoServiceProvider(2048)).ExportRSAPublicKey(), name) {}

        public User(byte[] id, string name)
        {
            Name = name;
            ID = id;
        }
    }
}